### ISSUE TITLE
genoooome

### ISSUE THREAD

**Issue by sojalei** [nheir/teeworlds#1]
what is genome??

**Comment by nheir** [comment]
i gave a try to unsupervised learning with some genetic algorithm.
Basically, the AI tries several objectives in an order given by this algorithm.
An objective is about getting HP, weapons, armor, flag etc
If an order allow the bot to live long enough, the order gets a good score.
The algorithm tries to guess the best order.

The way I did does not really work, but that makes the bots change behaviour, a bit :)
